In [2]:
from sklearn import preprocessing
import numpy as np

In [4]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [5]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [7]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [8]:
scaler

StandardScaler()

In [9]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [10]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [11]:
X_scaled = scaler.transform(X_train)

In [12]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
scaler.std_

AttributeError: 'StandardScaler' object has no attribute 'std_'